services:
  postgres:
    image: postgres:17-alpine
    container_name: ms_lab_db
    environment:
      POSTGRES_DB: ms_lab_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d ms_lab_db
      interval: 15s
      timeout: 15s
      retries: 5
    restart: unless-stopped


  liquibase:
    container_name: ms_lab_migrations
    image: liquibase/liquibase:4.29
    command:
        - --searchPath=/changesets
        - --changelog-file=master.xml
        - --driver=org.postgresql.Driver
        - --url=jdbc:postgresql://postgres:5432/ms_lab_db
        - --username=postgres
        - --password=postgres
        - update 
    volumes:
        - ./migrations:/changesets
    depends_on:
      postgres:
        condition: service_healthy

  ms_lab:
    build:
      context: .
      dockerfile: MS_Lab/Dockerfile
    container_name: ms_lab_backend
    ports:
      - "5258:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ms_lab_db;Username=postgres;Password=postgres
    depends_on:
      liquibase:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  postgres_data: