services:
  postgres:
    image: postgres:15-alpine
    container_name: ms_lab_db
    environment:
      POSTGRES_DB: ms_lab_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: ms_lab_adminer
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
  
  ms_lab:
    build:
      context: .
      dockerfile: MS_Lab/Dockerfile
    container_name: ms_lab_api
    ports:
      - "5258:8080"
      - "7122:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ms_lab_db;Username=postgres;Password=postgres
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: