global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'worker1'
    static_configs:
      - targets: 
        - 'ms_lab1:8080'
  
  - job_name: 'worker2'
    static_configs:
      - targets:
        - 'ms_lab2:8080'    
