CREATE TABLE IF NOT EXISTS events (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	description TEXT,
	place VARCHAR(200) NOT NULL,
	event_type INT NOT NULL,
	start_time_utc TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	end_time_utc TIMESTAMP NOT NULL,
	ticket_count BIGINT NOT NULL,
	price BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ticket_owners (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	surname VARCHAR(100) NOT NULL,
	phone VARCHAR(20),
	email VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS tickets (
	id BIGSERIAL PRIMARY KEY,
	ticket_number VARCHAR(50) NOT NULL UNIQUE,
	purchase_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
	owner_id BIGINT REFERENCES ticket_owners(id) ON DELETE CASCADE
);

